cmake_minimum_required(VERSION 3.15)
project(CrowSample)
set(INCLUDE_PATHS /usr/include)

message("Linking...")
add_library(core core.cpp)
target_include_directories(core PUBLIC ${INCLUDE_PATHS})
target_link_directories(core PUBLIC /usr/lib)
target_link_libraries(core PUBLIC pqxx)
target_include_directories(core PRIVATE ${PROJECT_SOURCE_DIR}/include)
message("Linked")
message("Load configs and generate executables...")
file(GLOB CONFIGS "../ConfigsForCrowBackend/settingsjson/*.json")
foreach(CONF ${CONFIGS})
	message("Config: ----")
	get_filename_component(NAME ${CONF} NAME_WE)
    add_executable(${NAME} main.cpp)
    target_link_libraries(${NAME} PRIVATE core)
    target_compile_definitions(${NAME} PRIVATE CONFIG_FILE="${CONF}")
endforeach()

add_executable(Test test.cpp)
target_link_libraries(Test PRIVATE core)
message("Ready.")
