CREATE TABLE "Felhasznalo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "felhasznalonev" char(30) UNIQUE,
  "email" varchar(60) UNIQUE,
  "jelszoHASH" text
);

CREATE TABLE "JogCsoport" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nev" varchar(30)
);

CREATE TABLE "JogCsoportHozzarendeles" (
  "jogCsoportID" int,
  "felhasznaloID" int,
  PRIMARY KEY ("jogCsoportID", "felhasznaloID")
);

CREATE TABLE "Sema" (
  "id" int PRIMARY KEY,
  "nev" varchar(30)
);

CREATE TABLE "HozzaferesKategoria" (
  "id" int PRIMARY KEY,
  "nev" int UNIQUE
);

CREATE TABLE "EngedelyezettSema" (
  "jogCsoportID" int,
  "semaID" int,
  "hozzaferesKategoriaID" int,
  PRIMARY KEY ("jogCsoportID", "semaID")
);

CREATE TABLE "Mertekegyseg" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(100) UNIQUE NOT NULL,
  "rovidites" varchar(6) UNIQUE NOT NULL
);

CREATE TABLE "Faj" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Alany" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kodnev" char(30) UNIQUE NOT NULL,
  "nev" varchar(100) NOT NULL,
  "nem" bit,
  "szuletes" date,
  "fajID" int
);

CREATE TABLE "HalottAlany" (
  "alanyID" int PRIMARY KEY,
  "halalIdopontja" date,
  "leiras" text
);

CREATE TABLE "Szerepkor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elvevezes" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Személy" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "szemelyiSzam" char(6) UNIQUE,
  "nev" varchar(100) NOT NULL,
  "anyjaNeve" varchar(100) NOT NULL,
  "szuletesiIdo" date NOT NULL
);

CREATE TABLE "Munkatars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "szerepkorID" int NOT NULL
);

CREATE TABLE "Ceg" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nev" varchar(200) UNIQUE NOT NULL
);

CREATE TABLE "Tapasztalat" (
  "munkatarsID" int,
  "cegID" int,
  "munkaviszonyKezdete" date,
  "munkakor" varchar(200),
  "leiras" text,
  "munkaviszonyVege" date,
  PRIMARY KEY ("munkatarsID", "cegID", "munkaviszonyKezdete")
);

CREATE TABLE "OktatasiIntezmeny" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nev" varchar(200) UNIQUE NOT NULL
);

CREATE TABLE "Szak" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "oktatasiIntezmenyID" int,
  "szakmegnevezes" varchar(200) UNIQUE NOT NULL
);

CREATE TABLE "Oklevel" (
  "munkatarsID" int,
  "oktatasiIntezmenyID" int,
  "szakID" int,
  "kezdesEve" int,
  "vegzesEve" int,
  "Ertekeles" int,
  "befejezetlen" bit,
  PRIMARY KEY ("munkatarsID", "oktatasiIntezmenyID", "szakID", "kezdesEve")
);

CREATE TABLE "Kiserlet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" int UNIQUE NOT NULL,
  "leiras" text
);

CREATE TABLE "KiserletVegrehajtas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "kiserletID" int,
  "mikor" date,
  "munkatarsID" int,
  PRIMARY KEY ("kiserletID", "mikor")
);

CREATE TABLE "KiserletLepesCsoport" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "elnevezes" varchar(100) UNIQUE NOT NULL,
  "leiras" text
);

CREATE TABLE "KLCsHozzarendeles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "fazis" INT GENERATED BY DEFAULT AS IDENTITY,
  "kiserletID" int,
  "kiserletLepesCsoportID" int,
  "csoportszam" int,
  "elnevezes" varchar(100) UNIQUE NOT NULL,
  "leiras" text,
  PRIMARY KEY ("fazis", "kiserletID", "kiserletLepesCsoportID")
);

CREATE TABLE "KLCsHozzarendelesVegrehajtas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "kiserletVegrehajtasID" int,
  "kLCsHozzarendelesID" int,
  "kezd" date,
  "vege" date,
  "munkatarsIDvezeto" int,
  PRIMARY KEY ("kiserletVegrehajtasID", "kLCsHozzarendelesID", "kezd")
);

CREATE TABLE "EpuletHelyseg" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "EpuletHelysegFerohely" (
  "epuletHelysegID" int,
  "kiserletCsoportID" int,
  "mennyien" int,
  PRIMARY KEY ("epuletHelysegID", "kiserletCsoportID")
);

CREATE TABLE "Atjaras" (
  "epuletHelysegID" int,
  "epuletHelysegIDcel" int,
  PRIMARY KEY ("epuletHelysegID", "epuletHelysegIDcel")
);

CREATE TABLE "KiserletLepes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "kiserletLepesCsoportID" int,
  "elnevezes" varchar(100),
  "epuletHelysegID" int,
  "leiras" text,
  PRIMARY KEY ("kiserletLepesCsoportID", "elnevezes")
);

CREATE TABLE "KiserletLepesSorrend" (
  "kiserletLepesID" int,
  "hanyadik" int,
  "kiserletLepesIDszuloelem" int,
  "csoportszam" int
);

CREATE TABLE "Valaszthato" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "ValaszthatoAnyag" (
  "kiserletLepesID" int,
  "anyagID" int,
  "csoportszam" int,
  PRIMARY KEY ("kiserletLepesID", "anyagID")
);

CREATE TABLE "ValaszthatoAlanyTipus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "kiserletLepesID" int,
  "vizsgalatElojegyzesID" int,
  "mennyi" int,
  "csoportszam" int,
  PRIMARY KEY ("kiserletLepesID", "vizsgalatElojegyzesID")
);

CREATE TABLE "ValaszthatoAlany" (
  "kLCsHozzarendelesVegrehajtasID" int,
  "alanyID" int,
  "valaszthatoAlanyTipusID" int,
  PRIMARY KEY ("kLCsHozzarendelesVegrehajtasID", "alanyID")
);

CREATE TABLE "ValasztasiLehetoseg" (
  "kiserletLepesID" int,
  "valaszthatoID" int,
  "csoportszam" int,
  PRIMARY KEY ("kiserletLepesID", "valaszthatoID")
);

CREATE TABLE "MegetetendoEtelek" (
  "kiserletLepesID" int,
  "anyagID" int,
  "mennyiseg" float,
  PRIMARY KEY ("kiserletLepesID", "anyagID")
);

CREATE TABLE "LepeshezTartozoVizsgalat" (
  "kiserletLepesID" int,
  "vizsgalatElojegyzesID" int,
  PRIMARY KEY ("kiserletLepesID", "vizsgalatElojegyzesID")
);

CREATE TABLE "KiserletlepesFeltetelesUgras" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "kiserletLepesID" int,
  "kiserletLepesIDcel" int,
  "rekurzivnakszant" bit,
  PRIMARY KEY ("kiserletLepesID", "kiserletLepesIDcel")
);

CREATE TABLE "KiserletLepesFeltetelesUgrasFeltetel" (
  "kiserletlepesFeltetelesUgrasID" int,
  "vizsgalatElojegyzesID" int,
  PRIMARY KEY ("kiserletlepesFeltetelesUgrasID", "vizsgalatElojegyzesID")
);

CREATE TABLE "KiserletResztvevo" (
  "kLCsHozzarendelesVegrehajtasID" int,
  "alanyID" int,
  "csoportszam" int,
  "bevonasDatuma" date,
  "kivonasDatuma" date,
  "alanyvizsgalata" text,
  PRIMARY KEY ("kLCsHozzarendelesVegrehajtasID", "alanyID")
);

CREATE TABLE "KiserletLepesVegrehajtas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "probalkozas" INT GENERATED BY DEFAULT AS IDENTITY,
  "kLCsHozzarendelesVegrehajtasID" int,
  "kiserletLepesID" int,
  "alanyID" int,
  "mikor" date,
  "munkatarsID" int,
  "sikeres" bit,
  "leiras" text,
  PRIMARY KEY ("probalkozas", "kLCsHozzarendelesVegrehajtasID", "kiserletLepesID", "alanyID")
);

CREATE TABLE "KiserletLepesVegrehajtasEsemeny" (
  "hanyadik" INT GENERATED BY DEFAULT AS IDENTITY,
  "kiserletLepesVegrehajtasID" int,
  "mikor" date,
  "gyorsleiras" varchar(200),
  "elemzes" text,
  PRIMARY KEY ("hanyadik", "kiserletLepesVegrehajtasID")
);

CREATE TABLE "KiserletLepesVegreHajtasValasztottAlany" (
  "kiserletLepesVegrehajtasID" int,
  "alanyID" int,
  PRIMARY KEY ("kiserletLepesVegrehajtasID", "alanyID")
);

CREATE TABLE "KiserletLepesVegreHajtasValasztottLehetoseg" (
  "kiserletLepesVegrehajtasID" int,
  "valaszthatoID" int,
  PRIMARY KEY ("kiserletLepesVegrehajtasID", "valaszthatoID")
);

CREATE TABLE "KiserletLepesVegreHajtasEtetes" (
  "kiserletLepesVegrehajtasID" int,
  "etetesID" int,
  PRIMARY KEY ("kiserletLepesVegrehajtasID", "etetesID")
);

CREATE TABLE "KiserletLepesVegreHajtasVizsgalat" (
  "kiserletLepesVegrehajtasID" int,
  "alanyVizsgalatID" int,
  PRIMARY KEY ("kiserletLepesVegrehajtasID", "alanyVizsgalatID")
);

CREATE TABLE "AlkotoreszTipus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Alkotoresz" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "alkotoreszTipusID" int,
  "alkotoreszIDazonbelul" int,
  "elnevezes" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "FajAlkotoresze" (
  "fajID" int,
  "alkotoreszID" int,
  PRIMARY KEY ("fajID", "alkotoreszID")
);

CREATE TABLE "VizsgalatTipus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "VizsgalatElojegyzes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vizsgalatTipusID" int,
  "mintfeltetelletezik" bit
);

CREATE TABLE "AlanyVizsgalat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "vizsgalatElojegyzesID" int PRIMARY KEY,
  "alanyID" int,
  "vizsgalatIdopont" date,
  "megjegyzes" text
);

CREATE TABLE "Tualjdonsag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(30) UNIQUE NOT NULL,
  "mertekegysegID" int
);

CREATE TABLE "AlanyTulajdonsag" (
  "vizsgalatID" int,
  "tulajdonsagID" int,
  "mennyi" float,
  "kevesebb" bit,
  "egyenlo" bit,
  PRIMARY KEY ("vizsgalatID", "tulajdonsagID")
);

CREATE TABLE "AlkotoreszTulajdonsag" (
  "vizsgalatID" int,
  "alkotoreszID" int,
  "tulajdonsagID" int,
  "mennyi" float,
  "kevesebb" bit,
  "egyenlo" bit,
  "leiras" text,
  PRIMARY KEY ("vizsgalatID", "alkotoreszID", "tulajdonsagID")
);

CREATE TABLE "Tunet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "elnevezes" varchar(100) UNIQUE NOT NULL,
  "leiras" text
);

CREATE TABLE "ErintettAlkotoresz" (
  "alkotoreszID" int,
  "tunetID" int,
  PRIMARY KEY ("alkotoreszID", "tunetID")
);

CREATE TABLE "TunetAllapot" (
  "vizsgalatID" int,
  "tunetID" int,
  "sulyossagMerteke" int,
  "kevesebb" bit,
  "egyenlo" bit,
  "leiras" text,
  PRIMARY KEY ("vizsgalatID", "tunetID")
);

CREATE TABLE "Anyag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nev" varchar(100) UNIQUE NOT NULL,
  "mennyiseg" float,
  "mertekegysegID" int
);

CREATE TABLE "ReceptVariacioNev" (
  "id" int PRIMARY KEY,
  "nev" varchar(30)
);

CREATE TABLE "Recept" (
  "anyagID" int,
  "anyagIDOsszetevo" int,
  "variacioNevID" int,
  "mennyiseg" float,
  PRIMARY KEY ("anyagID", "anyagIDOsszetevo", "variacioNevID")
);

CREATE TABLE "Etetes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "alanyID" int,
  "datum" date,
  "munkatarsIDseged" int,
  PRIMARY KEY ("alanyID", "datum")
);

CREATE TABLE "MegetetettEtelek" (
  "etetesID" int,
  "anyagID" int,
  "mennyiseg" float,
  "elteroIdopont" date,
  PRIMARY KEY ("etetesID", "anyagID")
);

CREATE TABLE "EtelIntolarencia" (
  "etetesID" int,
  "anyagID" int
);

CREATE TABLE "Tartalmaz" (
  "vizsgalatID" int,
  "alkotoreszID" int,
  "anyagID" int,
  "mennyiseg" float,
  "kevesebb" bit,
  "egyenlo" bit,
  PRIMARY KEY ("vizsgalatID", "alkotoreszID", "anyagID")
);

CREATE UNIQUE INDEX "U_KiserletLepesSorrend" ON "KiserletLepesSorrend" ("kiserletLepesID", "hanyadik", "kiserletLepesIDszuloelem", "csoportszam");

ALTER TABLE "HalottAlany" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "KiserletVegrehajtas" ADD FOREIGN KEY ("munkatarsID") REFERENCES "Munkatars" ("id");

ALTER TABLE "KiserletResztvevo" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "Etetes" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "AlanyVizsgalat" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "Recept" ADD FOREIGN KEY ("anyagID") REFERENCES "Anyag" ("id");

ALTER TABLE "Recept" ADD FOREIGN KEY ("anyagIDOsszetevo") REFERENCES "Anyag" ("id");

ALTER TABLE "Anyag" ADD FOREIGN KEY ("mertekegysegID") REFERENCES "Mertekegyseg" ("id");

ALTER TABLE "MegetetettEtelek" ADD FOREIGN KEY ("etetesID") REFERENCES "Etetes" ("id");

ALTER TABLE "MegetetettEtelek" ADD FOREIGN KEY ("anyagID") REFERENCES "Anyag" ("id");

ALTER TABLE "TunetAllapot" ADD FOREIGN KEY ("tunetID") REFERENCES "Tunet" ("id");

ALTER TABLE "TunetAllapot" ADD FOREIGN KEY ("vizsgalatID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "AlkotoreszTulajdonsag" ADD FOREIGN KEY ("vizsgalatID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "Alkotoresz" ADD FOREIGN KEY ("alkotoreszTipusID") REFERENCES "AlkotoreszTipus" ("id");

ALTER TABLE "AlkotoreszTulajdonsag" ADD FOREIGN KEY ("alkotoreszID") REFERENCES "Alkotoresz" ("id");

ALTER TABLE "Alany" ADD FOREIGN KEY ("fajID") REFERENCES "Faj" ("id");

ALTER TABLE "KiserletLepes" ADD FOREIGN KEY ("kiserletLepesCsoportID") REFERENCES "KiserletLepesCsoport" ("id");

ALTER TABLE "KiserletLepesVegrehajtas" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "KiserletLepesVegrehajtas" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "KiserletLepesVegrehajtas" ADD FOREIGN KEY ("munkatarsID") REFERENCES "Munkatars" ("id");

ALTER TABLE "Etetes" ADD FOREIGN KEY ("munkatarsIDseged") REFERENCES "Munkatars" ("id");

ALTER TABLE "Tapasztalat" ADD FOREIGN KEY ("munkatarsID") REFERENCES "Munkatars" ("id");

ALTER TABLE "Oklevel" ADD FOREIGN KEY ("munkatarsID") REFERENCES "Munkatars" ("id");

ALTER TABLE "Szak" ADD FOREIGN KEY ("oktatasiIntezmenyID") REFERENCES "OktatasiIntezmeny" ("id");

ALTER TABLE "Oklevel" ADD FOREIGN KEY ("szakID") REFERENCES "Szak" ("id");

ALTER TABLE "Oklevel" ADD FOREIGN KEY ("oktatasiIntezmenyID") REFERENCES "OktatasiIntezmeny" ("id");

ALTER TABLE "Tapasztalat" ADD FOREIGN KEY ("cegID") REFERENCES "Ceg" ("id");

ALTER TABLE "Munkatars" ADD FOREIGN KEY ("szerepkorID") REFERENCES "Szerepkor" ("id");

ALTER TABLE "ErintettAlkotoresz" ADD FOREIGN KEY ("tunetID") REFERENCES "Tunet" ("id");

ALTER TABLE "ErintettAlkotoresz" ADD FOREIGN KEY ("alkotoreszID") REFERENCES "Alkotoresz" ("id");

ALTER TABLE "Tartalmaz" ADD FOREIGN KEY ("vizsgalatID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "Tartalmaz" ADD FOREIGN KEY ("alkotoreszID") REFERENCES "Alkotoresz" ("id");

ALTER TABLE "Tartalmaz" ADD FOREIGN KEY ("anyagID") REFERENCES "Anyag" ("id");

ALTER TABLE "VizsgalatElojegyzes" ADD FOREIGN KEY ("vizsgalatTipusID") REFERENCES "VizsgalatTipus" ("id");

ALTER TABLE "AlkotoreszTulajdonsag" ADD FOREIGN KEY ("tulajdonsagID") REFERENCES "Tualjdonsag" ("id");

ALTER TABLE "AlanyTulajdonsag" ADD FOREIGN KEY ("vizsgalatID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "AlanyTulajdonsag" ADD FOREIGN KEY ("tulajdonsagID") REFERENCES "Tualjdonsag" ("id");

ALTER TABLE "KiserletLepesVegrehajtasEsemeny" ADD FOREIGN KEY ("kiserletLepesVegrehajtasID") REFERENCES "KiserletLepesVegrehajtas" ("id");

ALTER TABLE "KiserletlepesFeltetelesUgras" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "KiserletlepesFeltetelesUgras" ADD FOREIGN KEY ("kiserletLepesIDcel") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "Tualjdonsag" ADD FOREIGN KEY ("mertekegysegID") REFERENCES "Mertekegyseg" ("id");

ALTER TABLE "AlanyVizsgalat" ADD FOREIGN KEY ("vizsgalatElojegyzesID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "KiserletLepesFeltetelesUgrasFeltetel" ADD FOREIGN KEY ("kiserletlepesFeltetelesUgrasID") REFERENCES "KiserletlepesFeltetelesUgras" ("id");

ALTER TABLE "KiserletLepesFeltetelesUgrasFeltetel" ADD FOREIGN KEY ("vizsgalatElojegyzesID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "MegetetendoEtelek" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "MegetetendoEtelek" ADD FOREIGN KEY ("anyagID") REFERENCES "Anyag" ("id");

ALTER TABLE "LepeshezTartozoVizsgalat" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "LepeshezTartozoVizsgalat" ADD FOREIGN KEY ("vizsgalatElojegyzesID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "KiserletLepesVegreHajtasVizsgalat" ADD FOREIGN KEY ("kiserletLepesVegrehajtasID") REFERENCES "KiserletLepesVegrehajtas" ("id");

ALTER TABLE "KiserletLepesVegreHajtasEtetes" ADD FOREIGN KEY ("kiserletLepesVegrehajtasID") REFERENCES "KiserletLepesVegrehajtas" ("id");

ALTER TABLE "KiserletLepesVegreHajtasEtetes" ADD FOREIGN KEY ("etetesID") REFERENCES "Etetes" ("id");

ALTER TABLE "KiserletLepesVegreHajtasVizsgalat" ADD FOREIGN KEY ("alanyVizsgalatID") REFERENCES "AlanyVizsgalat" ("id");

ALTER TABLE "Atjaras" ADD FOREIGN KEY ("epuletHelysegID") REFERENCES "EpuletHelyseg" ("id");

ALTER TABLE "Atjaras" ADD FOREIGN KEY ("epuletHelysegIDcel") REFERENCES "EpuletHelyseg" ("id");

ALTER TABLE "KiserletLepes" ADD FOREIGN KEY ("epuletHelysegID") REFERENCES "EpuletHelyseg" ("id");

ALTER TABLE "EpuletHelysegFerohely" ADD FOREIGN KEY ("epuletHelysegID") REFERENCES "EpuletHelyseg" ("id");

ALTER TABLE "EpuletHelysegFerohely" ADD FOREIGN KEY ("kiserletCsoportID") REFERENCES "KiserletLepesCsoport" ("id");

ALTER TABLE "ValasztasiLehetoseg" ADD FOREIGN KEY ("valaszthatoID") REFERENCES "Valaszthato" ("id");

ALTER TABLE "ValasztasiLehetoseg" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "ValaszthatoAlanyTipus" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "ValaszthatoAnyag" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "ValaszthatoAnyag" ADD FOREIGN KEY ("anyagID") REFERENCES "Anyag" ("id");

ALTER TABLE "ValaszthatoAlany" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "KLCsHozzarendeles" ADD FOREIGN KEY ("kiserletID") REFERENCES "Kiserlet" ("id");

ALTER TABLE "KLCsHozzarendeles" ADD FOREIGN KEY ("kiserletLepesCsoportID") REFERENCES "KiserletLepesCsoport" ("id");

ALTER TABLE "ValaszthatoAlanyTipus" ADD FOREIGN KEY ("vizsgalatElojegyzesID") REFERENCES "VizsgalatElojegyzes" ("id");

ALTER TABLE "ValaszthatoAlany" ADD FOREIGN KEY ("valaszthatoAlanyTipusID") REFERENCES "ValaszthatoAlanyTipus" ("id");

ALTER TABLE "KiserletResztvevo" ADD FOREIGN KEY ("kLCsHozzarendelesVegrehajtasID") REFERENCES "KLCsHozzarendelesVegrehajtas" ("id");

ALTER TABLE "KiserletLepesVegrehajtas" ADD FOREIGN KEY ("kLCsHozzarendelesVegrehajtasID") REFERENCES "KLCsHozzarendelesVegrehajtas" ("id");

ALTER TABLE "ValaszthatoAlany" ADD FOREIGN KEY ("kLCsHozzarendelesVegrehajtasID") REFERENCES "KLCsHozzarendelesVegrehajtas" ("id");

ALTER TABLE "KiserletVegrehajtas" ADD FOREIGN KEY ("kiserletID") REFERENCES "Kiserlet" ("id");

ALTER TABLE "KLCsHozzarendelesVegrehajtas" ADD FOREIGN KEY ("kLCsHozzarendelesID") REFERENCES "KLCsHozzarendeles" ("id");

ALTER TABLE "KLCsHozzarendelesVegrehajtas" ADD FOREIGN KEY ("kiserletVegrehajtasID") REFERENCES "KiserletVegrehajtas" ("id");

ALTER TABLE "KiserletLepesVegreHajtasValasztottAlany" ADD FOREIGN KEY ("kiserletLepesVegrehajtasID") REFERENCES "KiserletLepesVegrehajtas" ("id");

ALTER TABLE "KiserletLepesVegreHajtasValasztottLehetoseg" ADD FOREIGN KEY ("kiserletLepesVegrehajtasID") REFERENCES "KiserletLepesVegrehajtas" ("id");

ALTER TABLE "KiserletLepesVegreHajtasValasztottLehetoseg" ADD FOREIGN KEY ("valaszthatoID") REFERENCES "Valaszthato" ("id");

ALTER TABLE "KiserletLepesVegreHajtasValasztottAlany" ADD FOREIGN KEY ("alanyID") REFERENCES "Alany" ("id");

ALTER TABLE "Alkotoresz" ADD FOREIGN KEY ("alkotoreszIDazonbelul") REFERENCES "Alkotoresz" ("id");

ALTER TABLE "FajAlkotoresze" ADD FOREIGN KEY ("alkotoreszID") REFERENCES "Alkotoresz" ("id");

ALTER TABLE "FajAlkotoresze" ADD FOREIGN KEY ("fajID") REFERENCES "Faj" ("id");

ALTER TABLE "KiserletLepesSorrend" ADD FOREIGN KEY ("kiserletLepesID") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "KiserletLepesSorrend" ADD FOREIGN KEY ("kiserletLepesIDszuloelem") REFERENCES "KiserletLepes" ("id");

ALTER TABLE "Munkatars" ADD FOREIGN KEY ("id") REFERENCES "Felhasznalo" ("id");

ALTER TABLE "Alany" ADD FOREIGN KEY ("id") REFERENCES "Felhasznalo" ("id");

ALTER TABLE "Recept" ADD FOREIGN KEY ("variacioNevID") REFERENCES "ReceptVariacioNev" ("id");

ALTER TABLE "JogCsoportHozzarendeles" ADD FOREIGN KEY ("jogCsoportID") REFERENCES "JogCsoport" ("id");

ALTER TABLE "JogCsoportHozzarendeles" ADD FOREIGN KEY ("felhasznaloID") REFERENCES "Felhasznalo" ("id");

ALTER TABLE "EngedelyezettSema" ADD FOREIGN KEY ("hozzaferesKategoriaID") REFERENCES "HozzaferesKategoria" ("id");

ALTER TABLE "EngedelyezettSema" ADD FOREIGN KEY ("semaID") REFERENCES "Sema" ("id");

ALTER TABLE "EngedelyezettSema" ADD FOREIGN KEY ("jogCsoportID") REFERENCES "JogCsoport" ("id");
